# Generated by Django 3.0.9 on 2021-02-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0002_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
