# Generated by Django 3.1.7 on 2021-02-26 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0004_auto_20210218_0518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='TargetLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_lang', models.CharField(choices=[('en', 'English'), ('ta', 'Tamil'), ('de', 'German')], max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoApp.project')),
            ],
        ),
        migrations.CreateModel(
            name='SourceLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_lang', models.CharField(choices=[('en', 'English'), ('ta', 'Tamil'), ('de', 'German')], max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoApp.project')),
            ],
        ),
    ]
